#!/usr/bin/env node

/**
 * Docker Helper Script for T Shop Telegram Bot
 * 
 * Usage:
 *   node docker-helper.mjs build           - Build Docker image
 *   node docker-helper.mjs up              - Start container with docker-compose
 *   node docker-helper.mjs down            - Stop container
 *   node docker-helper.mjs logs            - View container logs
 *   node docker-helper.mjs test            - Test if bot is running
 *   node docker-helper.mjs setup           - Interactive setup
 */

import { execSync, spawnSync } from "child_process";
import fs from "fs";
import path from "path";
import readline from "readline";

const botDir = process.cwd();
const envFile = path.join(botDir, ".env");
const envExampleFile = path.join(botDir, ".env.example");

function runCommand(cmd, description) {
  console.log(`\n🔧 ${description}...`);
  try {
    execSync(cmd, { stdio: "inherit" });
    console.log(`✅ ${description} successful`);
    return true;
  } catch (error) {
    console.error(`❌ ${description} failed`);
    return false;
  }
}

async function askQuestion(question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

async function setupEnv() {
  console.log("\n📝 Setting up .env file for Docker");
  console.log("================================\n");

  const botToken = await askQuestion(
    "Enter Telegram Bot Token (from @BotFather): "
  );
  const chatId = await askQuestion("Enter Chat ID (where orders are sent): ");
  const groupName =
    (await askQuestion("Enter Group Name [T Shop Support]: ")) ||
    "T Shop Support";
  const storeUrl =
    (await askQuestion(
      "Enter Store URL [https://tdigitalstore.web.app]: "
    )) || "https://tdigitalstore.web.app";
  const port = (await askQuestion("Enter Port [3001]: ")) || "3001";

  const envContent = `# Telegram Bot Configuration for Docker
# Generated by docker-helper.mjs

BOT_TOKEN=${botToken}
OWNER_CHAT_ID=${chatId}
GROUP_NAME=${groupName}
STORE_URL=${storeUrl}
PORT=${port}
NODE_ENV=production
`;

  fs.writeFileSync(envFile, envContent);
  console.log(`\n✅ .env file created at ${envFile}`);
  console.log("\nContent:");
  console.log(envContent);
}

async function testBot() {
  console.log("\n🧪 Testing Bot Container");
  console.log("========================\n");

  try {
    console.log("📡 Testing health endpoint...");
    const response = await fetch("http://localhost:3001/api/health", {
      timeout: 5000,
    });

    if (response.ok) {
      const data = await response.json();
      console.log("✅ Bot is running!");
      console.log("   Response:", data);
    } else {
      console.log("⚠️  Health check returned:", response.status);
    }
  } catch (error) {
    console.error("❌ Failed to connect to bot");
    console.error("   Make sure container is running: docker-compose ps");
    console.error("   View logs: docker-compose logs -f");
  }
}

async function main() {
  const command = process.argv[2];

  if (!command) {
    console.log(`
📦 T Shop Telegram Bot - Docker Helper

Usage:
  node docker-helper.mjs <command>

Commands:
  setup      Interactive setup wizard
  build      Build Docker image
  up         Start container with docker-compose
  down       Stop container
  logs       View container logs (follow)
  test       Test if bot is running
  ps         Show running containers
  shell      Get shell access to container
  clean      Remove image and containers

Example:
  node docker-helper.mjs setup  # First time setup
  node docker-helper.mjs up     # Start bot
  node docker-helper.mjs logs   # View logs
`);
    return;
  }

  switch (command) {
    case "setup":
      await setupEnv();
      console.log("\n📖 Next steps:");
      console.log("  1. Build image:  node docker-helper.mjs build");
      console.log("  2. Start bot:    node docker-helper.mjs up");
      console.log("  3. View logs:    node docker-helper.mjs logs");
      console.log("  4. Test bot:     node docker-helper.mjs test");
      break;

    case "build":
      if (!fs.existsSync(envFile)) {
        console.log(
          "⚠️  .env file not found. Running setup wizard first...\n"
        );
        await setupEnv();
      }
      runCommand(
        "docker build -t t-shop-bot:latest .",
        "Building Docker image"
      );
      console.log(
        "\n✅ Image built successfully!\n   Run: docker-compose up -d"
      );
      break;

    case "up":
      if (!fs.existsSync(envFile)) {
        console.log(
          "⚠️  .env file not found. Running setup wizard first...\n"
        );
        await setupEnv();
      }
      runCommand(
        "docker-compose up -d --build",
        "Starting bot container"
      );
      setTimeout(() => {
        console.log("\n📝 Next steps:");
        console.log("  View logs:  node docker-helper.mjs logs");
        console.log("  Test bot:   node docker-helper.mjs test");
      }, 2000);
      break;

    case "down":
      runCommand("docker-compose down", "Stopping bot container");
      break;

    case "logs":
      runCommand("docker-compose logs -f", "Following container logs");
      break;

    case "ps":
      runCommand("docker-compose ps", "Showing container status");
      break;

    case "test":
      await testBot();
      break;

    case "shell":
      runCommand(
        "docker exec -it t-shop-telegram-bot sh",
        "Opening container shell"
      );
      break;

    case "clean":
      console.log("\n🗑️  Cleaning up Docker resources...");
      runCommand("docker-compose down -v", "Removing containers");
      runCommand("docker rmi t-shop-bot:latest", "Removing image");
      console.log("\n✅ Cleanup complete");
      break;

    default:
      console.error(`❌ Unknown command: ${command}`);
      console.log(
        "Run: node docker-helper.mjs (with no args) for help"
      );
      process.exit(1);
  }
}

main().catch(console.error);
