version: '3.8'

services:
  t-shop-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t-shop-telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - t-shop-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  t-shop-network:
    driver: bridge
